// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP1JH1XQW-oU0ttkaNcnPmElEWvGttboA',
    appId: '1:372599305623:web:6f26a0b9684abeb4e480d2',
    messagingSenderId: '372599305623',
    projectId: 'qedic-40929',
    authDomain: 'qedic-40929.firebaseapp.com',
    storageBucket: 'qedic-40929.appspot.com',
    measurementId: 'G-2CM66KMSJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGuPfIJ-nv3GrmU4dOx4Kb0iKssRf7Nj4',
    appId: '1:372599305623:android:89d14a24d6e26743e480d2',
    messagingSenderId: '372599305623',
    projectId: 'qedic-40929',
    storageBucket: 'qedic-40929.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-tGwpeEC3ZLjFursnxBM5CAqrBeHK760',
    appId: '1:372599305623:ios:827b1bfd1b02e43de480d2',
    messagingSenderId: '372599305623',
    projectId: 'qedic-40929',
    storageBucket: 'qedic-40929.appspot.com',
    iosClientId: '372599305623-hn9vensuts1ot86pumm4up27bm1m9gp0.apps.googleusercontent.com',
    iosBundleId: 'com.one.qedic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-tGwpeEC3ZLjFursnxBM5CAqrBeHK760',
    appId: '1:372599305623:ios:827b1bfd1b02e43de480d2',
    messagingSenderId: '372599305623',
    projectId: 'qedic-40929',
    storageBucket: 'qedic-40929.appspot.com',
    iosClientId: '372599305623-hn9vensuts1ot86pumm4up27bm1m9gp0.apps.googleusercontent.com',
    iosBundleId: 'com.one.qedic',
  );
}
